version: "3.8"

services:
  web:
    build: .
    container_name: tainted_grail_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-tainted-grail-dev-key-change-in-production
    stdin_open: true
    tty: true
